version: '3.4'

services:
  rafrontend:
    image: kingdawnage/ra-frontend:latest
    container_name: ra-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
